### PR TITLE
updated arc-enabled-servers

### PR DESCRIPTION
**Pull request by skiddder**
the fork contains the following changes:
- new templates and scripts for coaches to create Azure VMs for the participants where the Azure guest agent is disabled, so they can use these VMs to onboard them via Azure Arc.
- updated the walkthrough description for challenge 2 to reflect changes in the Azure UI and existing policies and data collection rules.

The arc-enabled server experience now is fully functional using Azure Monitoring Agent only (no Automation account or OMS agents needed).

### CODE REVIEW

**Comment by TheFitzZZ** [comment]
Chellenge 2, Task 3 step 5 is not needed in my view, as the remediation of existing objects is done automatically: 
image

**Comment by TheFitzZZ** [comment]
Todo: 

- [ ] Clarify need to do manual remediation tasks. My take: will automatically be created upon assignment, even for existing objects
- [ ] Missing table in LAW prevents Task 5 (import data collection ruke for inventory)

**Comment by TheFitzZZ** [comment]
No need to create manual remediation 
image

**Comment by TheFitzZZ** [comment]
@skiddder please review and approve my changes.

**Review by TheFitzZZ — CHANGES_REQUESTED** [review]
Please verify my changes prior to approval

**Comment by TheFitzZZ** [comment]
Regression: manual remediation might be required for initiatives:
image
Only 2 of 6 were actually remediated - maybe because items weren't visible before?

**Review by skiddder — COMMENTED** [review]
looks fine now.

**Review by TheFitzZZ — APPROVED** [review]

**Pull request merged**
